# Generated by Django 5.2 on 2025-05-04 08:09

import builtins
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='note',
            name='text',
            field=models.CharField(verbose_name=builtins.max),
        ),
    ]
